// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIxFoea6rAjce5PLyEtNHMLk1DcVOs7ls',
    appId: '1:928114707036:web:058a8bfba41a4ec509f499',
    messagingSenderId: '928114707036',
    projectId: 'demoapp-dbee1',
    authDomain: 'demoapp-dbee1.firebaseapp.com',
    storageBucket: 'demoapp-dbee1.firebasestorage.app',
    measurementId: 'G-6DSLFX1QM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzRlgiPY4_LTX3BiaxO8TBfuFveDox7kA',
    appId: '1:928114707036:android:3d7f77260cf8020609f499',
    messagingSenderId: '928114707036',
    projectId: 'demoapp-dbee1',
    storageBucket: 'demoapp-dbee1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDIgW4lKVpZ2XWN2TN2mNUALsNqpolZug',
    appId: '1:928114707036:ios:a870f8f4bf58d26209f499',
    messagingSenderId: '928114707036',
    projectId: 'demoapp-dbee1',
    storageBucket: 'demoapp-dbee1.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );
}
